// Code generated by cue get go. DO NOT EDIT.

//cue:generate cue get go k8s.io/apimachinery/pkg/util/proxy

package proxy

import "net/http"

// Transport is a transport for text/html content that replaces URLs in html
// content with the prefix of the proxy server
#Transport: {
	Scheme:       string
	Host:         string
	PathPrepend:  string
	RoundTripper: http.#RoundTripper
}
