// Code generated by cue get go. DO NOT EDIT.

//cue:generate cue get go k8s.io/apimachinery/pkg/runtime/serializer/versioning

package versioning

_#codecIdentifier: {
	encodeGV?: string @go(EncodeGV)
	encoder?:  string @go(Encoder)
	name?:     string @go(Name)
}
