// Code generated by cue get go. DO NOT EDIT.

//cue:generate cue get go k8s.io/apimachinery/pkg/util/httpstream

// Package httpstream adds multiplexed streaming support to HTTP requests and
// responses via connection upgrades.
package httpstream
