// Code generated by cue get go. DO NOT EDIT.

//cue:generate cue get go k8s.io/apimachinery/pkg/runtime/serializer/streaming

// Package streaming implements encoder and decoder for streams
// of runtime.Objects over io.Writer/Readers.
package streaming

// Encoder is a runtime.Encoder on a stream.
#Encoder: _

// Decoder is a runtime.Decoder from a stream.
#Decoder: _

// Serializer is a factory for creating encoders and decoders that work over streams.
#Serializer: _
