// Code generated by cue get go. DO NOT EDIT.

//cue:generate cue get go k8s.io/apimachinery/pkg/util/errors

// Package errors implements various utility functions and types around errors.
package errors
