// Code generated by cue get go. DO NOT EDIT.

//cue:generate cue get go k8s.io/apimachinery/pkg/util/cache

package cache

// Clock defines an interface for obtaining the current time
#Clock: _

// realClock implements the Clock interface by calling time.Now()
_#realClock: {
}
