// Code generated by cue get go. DO NOT EDIT.

//cue:generate cue get go k8s.io/apimachinery/pkg/util/net

package net

// PortRange represents a range of TCP/UDP ports.  To represent a single port,
// set Size to 1.
#PortRange: {
	Base: int
	Size: int
}
