// Code generated by cue get go. DO NOT EDIT.

//cue:generate cue get go k8s.io/apimachinery/pkg/runtime/serializer/yaml

package yaml

import "k8s.io/apimachinery/pkg/runtime"

// yamlSerializer converts YAML passed to the Decoder methods to JSON.
_#yamlSerializer: {
	// the nested serializer
	Serializer: runtime.#Serializer
}
