// Code generated by cue get go. DO NOT EDIT.

//cue:generate cue get go k8s.io/apimachinery/pkg/runtime/serializer/protobuf

// Package protobuf provides a Kubernetes serializer for the protobuf format.
package protobuf
