// Code generated by cue get go. DO NOT EDIT.

//cue:generate cue get go k8s.io/apimachinery/pkg/util/yaml

package yaml

_#yamlSeparator: "\n---"

_#separator: "---"

// decoder is a convenience interface for Decode.
_#decoder: _

#JSONSyntaxError: {
	Offset: int64
	Err:    _ @go(,error)
}

#Reader: _
