// Code generated by cue get go. DO NOT EDIT.

//cue:generate cue get go k8s.io/apimachinery/pkg/util/framer

// Package framer implements simple frame decoding techniques for an io.ReadCloser
package framer
